Zinc:
  extensions:
    - ".zn"

  default:
    color: "#000000"

  identifier:
    color: "#0e9c94"

  number:
    color: "#0000aa"

  string:
    color: "#0000aa"

  comment:
    color: "#008800"
    single_line: "//"
    begin_multiline: "/*"
    end_multiline: "*/"

  group:
    - color: "#a71d5d"
      keywords:
        - "library"
        - "public"
        - "private"
        - "function"
      operators:
        - "->"
        - "("
        - ")"

    - color: "#FF1053"
      keywords:
        - "onInit"
        - "destroy"
        - "create"
