Zinc:
  extensions:
    - ".zn"

  default:
    color: "#000000"

  identifier:
    color: "#0e9c94"

  number:
    color: "#0000aa"

  string:
    color: "#0000aa"

  comment:
    color: "#008800"
    single_line: "//"
    begin_multiline: "/*"
    end_multiline: "*/"

  group:
    - color: "#a71d5d"
      keywords:
        - "library"

    - color: "#a71d5d"
      keywords:
        - "public"
        - "private"
        - "type"
        - "struct"
        - "extends"
        - "module"
        - "requires"
        - "method"
        - "static"

    - color: "#aa5553"
      operators:
        - "&&"
        - "||"
        - "=="
        - "!="
        - "!"
        - "("
        - ")"
        - "{"
        - "}"
        - ">="
        - "<="
        - ">"
        - ">"
        - "="
        - ";"
        - "->"
        
    - color: "#FF1053"
      keywords:
        - "onInit"
        - "destroy"
        - "create"
