# Zinc Syntax Highligthing
Zinc:
  extensions:
    - ".zn"

  default:
    color: "#24292e"

  identifier:
    color: "#7b9c0e"

  number:
    color: "#745296"

  string:
    color: "#8B9EB7"

  comment:
    color: "#969896"
    single_line: "//"
    begin_multiline: "/*"
    end_multiline: "*/"

  group:
    - color: "#a71d5d"
      keywords:
        - "ability"
        - "agent"
        - "aidifficulty"
        - "array"
        - "attacktype"
        - "blendmode"
        - "boolean"
        - "boolexpr"
        - "buff"
        - "button"
        - "camerafield"
        - "camerasetup"
        - "code"
        - "conditionfunc"
        - "damagetype"
        - "defeatcondition"
        - "destructable"
        - "dialog"
        - "dialogevent"
        - "effect"
        - "effecttype"
        - "event"
        - "eventid"
        - "fgamestate"
        - "filterfunc"
        - "fogmodifier"
        - "fogstate"
        - "force"
        - "gamecache"
        - "gamedifficulty"
        - "gameevent"
        - "gamespeed"
        - "gametype"
        - "group"
        - "handle"
        - "hashtable"
        - "igamestate"
        - "image"
        - "integer"
        - "item"
        - "itempool"
        - "itemtype"
        - "key"
        - "leaderboard"
        - "lightning"
        - "limitop"
        - "location"
        - "mapcontrol"
        - "mapdensity"
        - "mapflag"
        - "mapsetting"
        - "mapvisibility"
        - "multiboard"
        - "multiboarditem"
        - "nothing"
        - "pathingtype"
        - "placement"
        - "player"
        - "playercolor"
        - "playerevent"
        - "playergameresult"
        - "playerscore"
        - "playerslotstate"
        - "playerstate"
        - "playerunitevent"
        - "quest"
        - "questitem"
        - "race"
        - "racepreference"
        - "raritycontrol"
        - "real"
        - "rect"
        - "region"
        - "sound"
        - "soundtype"
        - "startlocprio"
        - "string"
        - "terraindeformation"
        - "texmapflags"
        - "texttag"
        - "thistype"
        - "timer"
        - "timerdialog"
        - "trackable"
        - "trigger"
        - "triggeraction"
        - "triggercondition"
        - "ubersplat"
        - "unit"
        - "unitevent"
        - "unitpool"
        - "unitstate"
        - "unittype"
        - "version"
        - "volumegroup"
        - "weapontype"
        - "weathereffect"
        - "widget"
        - "widgetevent"

    - color: "#FF1053"
      keywords:
        - "library"
        - "//! zinc"
        - "//! endzinc"
