Zinc:
  extensions:
    - ".zn"

  default:
    color: "#24292e"

  identifier:
    color: "#7b9c0e"

  number:
    color: "#745296"

  string:
    color: "#8B9EB7"

  comment:
    color: "#969896"
    single_line: "//"
    begin_multiline: "/*"
    end_multiline: "*/"

  group:
    - color: "#a71d5d"
      keywords:
        - "library"
        - "{"
        - "}"
        - "struct"
        - "extends"
        - "module"

    - color: "#FF1053"
      keywords:
        - "printf"
        - "putchar"
        - "getchar"
