Zinc:
  extensions:
    - ".zn"

  default:
    color: "#000000"

  identifier:
    color: "#000000"

  number:
    color: "#0000aa"

  string:
    color: "#0000aa"

  comment:
    color: "#008800"
    single_line: "//"
    begin_multiline: "/*"
    end_multiline: "*/"

  group:
    - color: "#a71d5d"
      keywords:
        - "library"
        - "public"
        - "private"
        - "type"
        - "struct"
        - "extends"
        - "module"
        - "requires"
        - "method"
        - "static"

    - color: "#aa5553"
      operators:
        - "&&"
        - "||"
        - "=="
        - "!="
        - "!"
        - "("
        - ")"
        - "{"
        - "}"
        - ">="
        - "<="
        - ">"
        - ">"
        - "="
        - ";"
        - "->"
        
    - color: "#532c8c"
      keywords:
        - "ability"
        - "agent"
        - "aidifficulty"
        - "alliancetype"
        - "array"
        - "attacktype"
        - "blendmode"
        - "boolean"
        - "boolexpr"
        - "buff"
        - "button"
        - "camerafield"
        - "camerasetup"
        - "code"
        - "conditionfunc"
        - "damagetype"
        - "defeatcondition"
        - "destructable"
        - "dialog"
        - "dialogevent"
        - "effect"
        - "event"
        - "eventid"
        - "fgamestate"
        - "filterfunc"
        - "fogmodifier"
        - "fogstate"
        - "force"
        - "gamecache"
        - "gamedifficulty"
        - "gameevent"
        - "gamespeed"
        - "gametype"
        - "group"
        - "handle"
        - "hashtable"
        - "igamestate"
        - "image"
        - "integer"
        - "item"
        - "itempool"
        - "itemtype"
        - "key"
        - "leaderboard"
        - "lightning"
        - "limitop"
        - "location"
        - "mapcontrol"
        - "mapdensity"
        - "mapflag"
        - "mapsetting"
        - "mapvisibility"
        - "multiboard"
        - "multiboarditem"
        - "nothing"
        - "pathingtype"
        - "placement"
        - "player"
        - "playercolor"
        - "playerevent"
        - "playergameresult"
        - "playerscore"
        - "playerunitevent"
        - "quest"
        - "questitem"
        - "race"
        - "racepreference"
        - "raritycontrol"
        - "real"
        - "race"
        - "rect"
        - "region"
        - "sound"
        - "soundtype"
        - "startlocprio"
        - "string"
        - "terraindeformation"
        - "texmapflags"
        - "texttag"
        - "this"
        - "thistype"
        - "timer"
        - "timerdialog"
        - "trackable"
        - "trigger"
        - "triggeraction"
        - "triggercondition"
        - "ubersplat"
        - "unit"
        - "unitevent"
        - "unitpool"
        - "unitstate"
        - "unittype"
        - "version"
        - "volumegroup"
        - "weapontype"
        - "weathereffect"
        - "widget"
        - "widgetevent"
