Zinc:
  extensions:
    - ".zn"

  default:
    color: "#000000"

  identifier:
    color: "#000000"

  number:
    color: "#0000aa"

  string:
    color: "#0000aa"

  comment:
    color: "#008800"
    single_line: "//"
    begin_multiline: "/*"
    end_multiline: "*/"

  group:
    - color: "#a71d5d"
      keywords:
        - "library"
        - "requires"
        - "optional"
       
    - color: "#532c8c"
      keywords:
        - "ability"
        - "agent"
        - "aidifficulty"
        - "alliancetype"
        - "array"
        - "attacktype"
        - "blendmode"
        - "boolean"
        - "boolexpr"
        - "buff"
        - "button"
        - "camerafield"
        - "camerasetup"
        - "code"
        - "conditionfunc"
        - "damagetype"
        - "defeatcondition"
        - "destructable"
        - "dialog"
        - "dialogevent"
        - "effect"
        - "event"
        - "eventid"
        - "false"
        - "fgamestate"
        - "filterfunc"
        - "fogmodifier"
        - "fogstate"
        - "force"
        - "gamecache"
        - "gamedifficulty"
        - "gameevent"
        - "gamespeed"
        - "gametype"
        - "group"
        - "handle"
        - "hashtable"
        - "igamestate"
        - "image"
        - "integer"
        - "item"
        - "itempool"
        - "itemtype"
        - "key"
        - "leaderboard"
        - "lightning"
        - "limitop"
        - "location"
        - "mapcontrol"
        - "mapdensity"
        - "mapflag"
        - "mapsetting"
        - "mapvisibility"
        - "multiboard"
        - "multiboarditem"
        - "nothing"
        - "null"
        - "pathingtype"
        - "placement"
        - "player"
        - "playercolor"
        - "playerevent"
        - "playergameresult"
        - "playerscore"
        - "playerunitevent"
        - "quest"
        - "questitem"
        - "race"
        - "racepreference"
        - "raritycontrol"
        - "real"
        - "race"
        - "rect"
        - "region"
        - "sound"
        - "soundtype"
        - "startlocprio"
        - "string"
        - "terraindeformation"
        - "texmapflags"
        - "texttag"
        - "this"
        - "thistype"
        - "timer"
        - "timerdialog"
        - "trackable"
        - "trigger"
        - "triggeraction"
        - "triggercondition"
        - "true"
        - "ubersplat"
        - "unit"
        - "unitevent"
        - "unitpool"
        - "unitstate"
        - "unittype"
        - "version"
        - "volumegroup"
        - "weapontype"
        - "weathereffect"
        - "widget"
        - "widgetevent"

    - color: "#aa5553"
      operators:
        - "&&"
        - "||"
        - "+"
        - "-"
        - "/"
        - "*"
        - "="
        - "!"
        - "("
        - ")"
        - "{"
        - "}"
        - ">"
        - "<"
        - "="
        - ";"
        - "["
        - "]"
        - "'"

    - color: "#7a0757"
      keywords:
        - "public"
        - "private"
        - "type"
        - "struct"
        - "extends"
        - "module"
        - "function"
        - "constant"
       
      operators: 
        - "->"
       
    - color: "#087a69"
      keywords:
        - "while"
        - "for"
        - "break"
        - "return"
        - "if"
        - "else"
        - "static"
        - "method"
        - "operator"
           
    - color: "#968800"
      multiline:
        - begin: "$"
          end:   "$"
          
    - color: "#c4c4c4"
      keywords:
        - "debug"
        - "DEBUG_MODE"

Jass:
  extensions:
    - ".j"

  default:
    color: "#000000"

  identifier:
    color: "#000000"

  number:
    color: "#0000aa"

  string:
    color: "#0000aa"

  comment:
    color: "#008800"
    single_line: "//"
    begin_multiline: "/*"
    end_multiline: "*/"

  group:
    - color: "#a71d5d"
      keywords:
        - "library"
        - "endlibrary"
        - "requires"
        - "needs"
        - "uses"
        - "optional"
        - "scope"
        - "endscope"
        - "initializer"
       
    - color: "#532c8c"
      keywords:
        - "ability"
        - "agent"
        - "aidifficulty"
        - "alliancetype"
        - "array"
        - "attacktype"
        - "blendmode"
        - "boolean"
        - "boolexpr"
        - "buff"
        - "button"
        - "camerafield"
        - "camerasetup"
        - "code"
        - "conditionfunc"
        - "damagetype"
        - "defeatcondition"
        - "destructable"
        - "dialog"
        - "dialogevent"
        - "effect"
        - "event"
        - "eventid"
        - "false"
        - "fgamestate"
        - "filterfunc"
        - "fogmodifier"
        - "fogstate"
        - "force"
        - "gamecache"
        - "gamedifficulty"
        - "gameevent"
        - "gamespeed"
        - "gametype"
        - "group"
        - "handle"
        - "hashtable"
        - "igamestate"
        - "image"
        - "integer"
        - "item"
        - "itempool"
        - "itemtype"
        - "key"
        - "keyword"
        - "leaderboard"
        - "lightning"
        - "limitop"
        - "location"
        - "mapcontrol"
        - "mapdensity"
        - "mapflag"
        - "mapsetting"
        - "mapvisibility"
        - "multiboard"
        - "multiboarditem"
        - "nothing"
        - "null"
        - "pathingtype"
        - "placement"
        - "player"
        - "playercolor"
        - "playerevent"
        - "playergameresult"
        - "playerscore"
        - "playerunitevent"
        - "quest"
        - "questitem"
        - "race"
        - "racepreference"
        - "raritycontrol"
        - "real"
        - "race"
        - "rect"
        - "region"
        - "sound"
        - "soundtype"
        - "startlocprio"
        - "string"
        - "super"
        - "terraindeformation"
        - "texmapflags"
        - "texttag"
        - "this"
        - "thistype"
        - "timer"
        - "timerdialog"
        - "trackable"
        - "trigger"
        - "triggeraction"
        - "triggercondition"
        - "true"
        - "ubersplat"
        - "unit"
        - "unitevent"
        - "unitpool"
        - "unitstate"
        - "unittype"
        - "version"
        - "volumegroup"
        - "weapontype"
        - "weathereffect"
        - "widget"
        - "widgetevent"

    - color: "#aa5553"
      keywords:
        - "and"
        - "or"
        - "not"
       
      operators:
        - "+"
        - "-"
        - "/"
        - "*"
        - "="
        - "("
        - ")"
        - "{"
        - "}"
        - ">"
        - "<"
        - "="
        - "["
        - "]"
        - ":"

    - color: "#7a0757"
      keywords:
        - "globals"
        - "endglobals"
        - "public"
        - "private"
        - "type"
        - "struct"
        - "endstruct"
        - "extends"
        - "module"
        - "endmodule"
        - "implement"
        - "function"
        - "endfunction"
        - "constant"
        - "takes"
        - "returns"
        - "interface"
        - "endinterface"
        - "hook"

    - color: "#087a69"
      keywords:
        - "local"
        - "set"
        - "call"
        - "exitwhen"
        - "return"
        - "if"
        - "then"
        - "else"
        - "endif"
        - "static"
        - "method"
        - "endmethod"
        - "operator"
        - "readonly"
        - "stub"
        - "delegate"
           
    - color: "#968800"
      multiline:
        - begin: "$"
          end:   "$"
         
    - color: "#c4c4c4"
      keywords:
        - "debug"
        - "DEBUG_MODE"
