# Syntax Highlighter for Zinc.
Zinc:
  extensions:
    - ".zn"
    - ".j"

  default:
    color: "#24292e"

  identifier:
    color: "#7b9c0e"

  number:
    color: "#6564ba"

  string:
    color: "#4c5d75"

  comment:
    color: "#969896"
    single_line: "//"

  group:
    - color: "#F00BAF"
      operators:
        - "=="
        - "!="
        - "<="
        - ">="
        - "!"
        - "||"
        - "&&"

  group:
    - color: "#FF00FF"
        multiline:
          - begin: "//! zinc"
            end: "//! endzinc"

  group:
    # Native types
    - color: "#a71d5d"
      keywords:
        - "ability"
        - "agent"
        - "aidifficulty"
        - "array"
        - "attacktype"
        - "blendmode"
        - "boolean"
        - "boolexpr"
        - "buff"
        - "button"
        - "camerafield"
        - "camerasetup"
        - "code"
        - "conditionfunc"
        - "damagetype"
        - "defeatcondition"
        - "destructable"
        - "dialog"
        - "dialogevent"
        - "effect"
        - "effecttype"
        - "event"
        - "eventid"
        - "fgamestate"
        - "filterfunc"
        - "fogmodifier"
        - "fogstate"
        - "force"
        - "gamecache"
        - "gamedifficulty"
        - "gameevent"
        - "gamespeed"
        - "gametype"
        - "group"
        - "handle"
        - "hashtable"
        - "igamestate"
        - "image"
        - "integer"
        - "item"
        - "itempool"
        - "itemtype"
        - "key"
        - "leaderboard"
        - "lightning"
        - "limitop"
        - "location"
        - "mapcontrol"
        - "mapdensity"
        - "mapflag"
        - "mapsetting"
        - "mapvisibility"
        - "multiboard"
        - "multiboarditem"
        - "nothing"
        - "pathingtype"
        - "placement"
        - "player"
        - "playercolor"
        - "playerevent"
        - "playergameresult"
        - "playerscore"
        - "playerslotstate"
        - "playerstate"
        - "playerunitevent"
        - "quest"
        - "questitem"
        - "race"
        - "racepreference"
        - "raritycontrol"
        - "real"
        - "rect"
        - "region"
        - "sound"
        - "soundtype"
        - "startlocprio"
        - "string"
        - "terraindeformation"
        - "texmapflags"
        - "texttag"
        - "thistype"
        - "timer"
        - "timerdialog"
        - "trackable"
        - "trigger"
        - "triggeraction"
        - "triggercondition"
        - "ubersplat"
        - "unit"
        - "unitevent"
        - "unitpool"
        - "unitstate"
        - "unittype"
        - "version"
        - "volumegroup"
        - "weapontype"
        - "weathereffect"
        - "widget"
        - "widgetevent"

    - color: "#fc1153"
      keywords:
        - "library"
    
    # Non-Jassy Word
    - color: "#af2652"
      keywords:
        - "while"
        - "for"
        - "type"
        - "extends"
