#
#   nel
#

Zinc:
  extensions:
    - ".zn"

  default:
    - "#000000"

  identifier:
    - "#348725"

  number:
    - "#0000aa"

  string:
    - "#0000aa"

  comment:
    - "#008800"
      single_line:
        - "//"
      begin_multiline:
        - "/*"
      end_multiline:
        - "*/"
    
vJass:
  extensions:
    - ".j"
  default:
    - "#000000"

  identifier:
    - "#348725"

  number:
    - "#0000aa"

  string:
    - "#0000aa"

  comment:
    - "#008800"
      single_line:
        - "//"
      begin_multiline:
        - "/*"
      end_multiline:
        - "*/"
