#
#   nel
#

Zinc:
  extensions:
    - ".zn"

  default:
    color: "#000000"

  identifier:
    color: "#348725"

  number:
    color: "#0000aa"

  string:
    color: "#0000aa"

  comment:
    color: "#008800"
    single_line: "//"
    begin_multiline: "/*"
    end_multiline: "*/"
